//! Independent G1 articulation in the sole runtime world.
pub mod agile_runner;
pub mod assembly;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_admission;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_assist;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_center;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_grip;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_hold;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_lowering;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_navigation;
pub mod mobile_open;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_raise;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_release;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_restore;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_thumb;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod mobile_wait;
pub mod runner;
pub mod static_environment;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod static_grasp;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod static_observe;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod static_observed_place;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod static_place;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod static_startup;
#[cfg(feature = "g1_constraint_diagnostic")]
pub mod static_transfer;
pub mod task_background;
pub mod task_objects;
pub mod task_policy;
pub mod task_runner;
pub mod task_shelf;
pub mod worker;
