"""Named Move terrain and horizontal-impulse adapters for pinned mjlab.

These prepare independent scenes; they do not alter the frozen flat baseline.
Terrain generation and impulse timers remain owned by upstream mjlab. Scene
contact roles, actual surface measurements and capacity checks must be wired
before training. A generated scene alone never grants terrain qualification.
"""
from __future__ import annotations

import copy
from math import isfinite, radians, tan

import mujoco
import torch
from mjlab.envs.mdp.events import apply_body_impulse
from mjlab.managers.event_manager import EventTermCfg
from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.sensor import ContactMatch, ContactSensorCfg
from mjlab.terrains import TerrainEntityCfg, TerrainGeneratorCfg
from mjlab.terrains import config as terrain_presets
from mjlab.utils.lab_api.math import quat_apply
from mjlab.utils.spec_config import CollisionCfg, GeomCfg

REVISION = "goose_move_mature_scenes_v1"
POLICY_DT_S = .02
REQUIRED_STEP_HEIGHTS_M = (.005, .010, .020)
CHALLENGE_STEP_HEIGHT_M = .050


def make_move_terrain(*, ground_model, seed: int, height_m: float,
                      evaluation: bool = False, ground_name: str = "ground"):
    """Reuse native rough, ramp and scattered-box terrain generators.

    Curriculum levels are generated by upstream mjlab. Formal scenes pin the
    difficulty to one and each box to the requested height; training scenes
    vary box heights. Random widths, lengths, yaw and locations remain native.
    Stepping-stone presets with a two-meter pit are deliberately not inherited.
    Contact properties come from the actual compiled frozen ground, never the
    upstream generator's different defaults. Route coverage must be measured
    independently during task evaluation.
    """
    if (isinstance(seed, bool) or not isinstance(seed, int) or seed < 0
            or height_m not in (*REQUIRED_STEP_HEIGHTS_M, CHALLENGE_STEP_HEIGHT_M)):
        raise ValueError("Move terrain requires a fixed seed and named height tier")
    ground = ground_model.geom(ground_name).id
    if not (ground_model.geom_contype[ground] or ground_model.geom_conaffinity[ground]):
        raise ValueError("Terrain must inherit a colliding frozen ground")
    continuous = {name: tuple(getattr(ground_model, "geom_" + name)[ground])
        for name in ("friction", "solref", "solimp")}
    continuous.update({name: float(getattr(ground_model, "geom_" + name)[ground])
        for name in ("margin", "gap", "solmix")})
    collision = CollisionCfg(geom_names_expr=(".*",),
        contype=int(ground_model.geom_contype[ground]),
        conaffinity=int(ground_model.geom_conaffinity[ground]),
        condim=int(ground_model.geom_condim[ground]),
        priority=int(ground_model.geom_priority[ground]), **continuous)
    low = height_m if evaluation else .5 * height_m
    slope = tan(radians(5.))
    terrains = {
        "flat": terrain_presets.flat(proportion=.25),
        "random_rough": terrain_presets.random_rough(proportion=.2,
            noise_range=(-.5 * height_m, .5 * height_m), noise_step=.001,
            horizontal_scale=.05, vertical_scale=.001),
        "slope_positive": terrain_presets.hf_pyramid_slope(proportion=.15,
            slope_range=(slope, slope) if evaluation else (0., slope),
            horizontal_scale=.05, vertical_scale=.001, platform_width=.8),
        "slope_negative": terrain_presets.hf_pyramid_slope_inv(proportion=.15,
            slope_range=(slope, slope) if evaluation else (0., slope),
            horizontal_scale=.05, vertical_scale=.001, platform_width=.8),
        "staggered_steps": terrain_presets.random_spread_boxes(proportion=.25,
            num_boxes=36, box_width_range=(.15, .35),
            box_length_range=(.15, .45), box_height_range=(low, height_m),
            box_yaw_range=(-30., 30.), add_floor=True, platform_width=.8),
    }
    generator = TerrainGeneratorCfg(seed=seed, size=(4., 4.),
        num_rows=1 if evaluation else 4, num_cols=len(terrains),
        curriculum=True, difficulty_range=(1., 1.) if evaluation else (0., 1.),
        border_width=1., border_height=.02, sub_terrains=terrains)
    return TerrainEntityCfg(terrain_type="generator", terrain_generator=generator,
        max_init_terrain_level=0, textures=(), materials=(), lights=(),
        collisions=(collision,), geoms=(GeomCfg(geom_names_expr=(".*",),
            group=int(ground_model.geom_group[ground])),))


def with_move_terrain(cfg, *, ground_model, seed: int, height_m: float,
                      evaluation: bool = False, ground_name: str = "ground"):
    """Assemble native terrain in a separate copy of the flat scene config.

    Keep the original scene callback that copies native solver options. Remove
    its plane after it runs so a hidden infinite floor cannot support rough
    terrain episodes. Ground-contact sensors retain their primary matches,
    fields and history, and instead match the native terrain body.

    This adapter only assembles scenes. Reset origins, terrain-relative foot
    measurements, capacity and GPU rollout still require independent admission.
    Native explicit material pairs need a separately frozen mapping and are
    rejected rather than discarded or expanded with guessed mixing rules.
    """
    if cfg.scene.terrain is not None or cfg.scene.spec_fn is None:
        raise ValueError("Move terrain requires a flat native scene callback")
    if ground_model.npair:
        raise ValueError("Explicit ground material pairs need a frozen terrain mapping")
    result = copy.deepcopy(cfg)
    result.scene.terrain = make_move_terrain(ground_model=ground_model, seed=seed,
        height_m=height_m, evaluation=evaluation, ground_name=ground_name)
    flat_scene_callback = result.scene.spec_fn

    def replace_native_plane(spec):
        flat_scene_callback(spec)
        ground = spec.geom(ground_name)
        if ground is None or ground.type != mujoco.mjtGeom.mjGEOM_PLANE:
            raise ValueError("Native callback did not create the declared ground plane")
        for pair in spec.pairs:
            if ground_name in (pair.geomname1, pair.geomname2):
                raise ValueError("Terrain cannot remove a plane with explicit material pairs")
        spec.delete(ground)

    result.scene.spec_fn = replace_native_plane
    matched = 0
    for sensor in result.scene.sensors:
        if (isinstance(sensor, ContactSensorCfg) and sensor.secondary is not None
                and sensor.secondary.mode == "geom"
                and sensor.secondary.pattern == ground_name
                and sensor.secondary.entity is None):
            sensor.secondary = ContactMatch(mode="body", pattern="terrain")
            matched += 1
    if not matched:
        raise ValueError("Native terrain requires declared ground-contact sensors")
    return result


class HorizontalBodyImpulse(apply_body_impulse):
    """Native impulse lifecycle with a declared one-control-Tick horizontal J.

    The upstream event samples direction and manages expiration/reset. This
    adapter projects a newly sampled force onto XY and sets its magnitude to
    J/20ms. Holding that wrench across four physical substeps delivers the same
    impulse as one20ms step. No qpos, qvel, action or drive history is written.
    Actual integrated force must still be recorded during real qualification.
    """

    def __init__(self, cfg, env):
        impulse = cfg.params["impulse_ns"]
        if (isinstance(impulse, bool) or not isfinite(impulse) or impulse <= 0
                or abs(env.step_dt - POLICY_DT_S) > 1e-12):
            raise ValueError("Horizontal impulse requires positive SI J and50Hz control")
        duration = cfg.params["duration_s"]
        if duration != (POLICY_DT_S, POLICY_DT_S):
            raise ValueError("Named impulses last exactly one20ms control Tick")
        super().__init__(cfg, env)
        self._impulse_ns = float(impulse)

    def __call__(self, env, env_ids, *, impulse_ns, **kwargs):
        if impulse_ns != self._impulse_ns:
            raise ValueError("Frozen impulse magnitude changed during the scene")
        before = self._active.clone()
        super().__call__(env, env_ids, **kwargs)
        ids = ((~before) & self._active).nonzero().flatten()
        if not len(ids):
            return
        wrench = self._asset.data.body_external_wrench[ids][:, self._body_ids]
        forces = wrench[..., :3].clone()
        forces[..., 2] = 0.
        norm = forces.norm(dim=-1, keepdim=True)
        fallback = torch.zeros_like(forces)
        fallback[..., 0] = 1.
        direction = torch.where(norm > 1e-12, forces / norm.clamp_min(1e-12), fallback)
        forces = direction * (self._impulse_ns / POLICY_DT_S)
        torques = torch.zeros_like(forces)
        if self._body_point_offset is not None:
            quat = self._asset.data.body_com_quat_w[ids][:, self._body_ids]
            offset = quat_apply(quat.reshape(-1, 4),
                self._body_point_offset.expand(len(ids) * self._num_bodies, 3))
            torques = torch.cross(offset.reshape_as(forces), forces, dim=-1)
        self._asset.write_external_wrench_to_sim(forces, torques,
            env_ids=ids, body_ids=self._body_ids)


def make_move_impulse(*, impulse_ns: float, body_name: str = "torso",
                      body_point_offset=(0., 0., 0.)):
    """Native step event; impulse tiers remain separate from real collisions."""
    if (isinstance(impulse_ns, bool) or impulse_ns not in (.5, 1., 3.) or not body_name
            or len(body_point_offset) != 3
            or not all(isfinite(value) for value in body_point_offset)):
        raise ValueError("Move impulse requires a named tier, body and finite SI offset")
    return EventTermCfg(func=HorizontalBodyImpulse, mode="step", params={
        "impulse_ns": float(impulse_ns), "force_range": (-1., 1.),
        "torque_range": (0., 0.), "duration_s": (POLICY_DT_S, POLICY_DT_S),
        "cooldown_s": (3., 6.), "body_point_offset": tuple(body_point_offset),
        "asset_cfg": SceneEntityCfg("robot", body_names=(body_name,))})
