#!/usr/bin/env python3
"""Diagnostic original Homie/PhysX standing reference, never Bevy qualification.

The default invocation only verifies immutable files. --run-source starts Isaac
Sim and must be scheduled with the task's GPU owner. Source physics is 200 Hz,
WBC 50 Hz; this never changes the application's required 50/50 timing.
"""

from __future__ import annotations

import argparse
from contextlib import contextmanager
import hashlib
import importlib.metadata
import json
import math
from pathlib import Path
import resource
import subprocess
import sys
import time


ARENA_REV = "7d75c95934c51a0318c957a8831e862ca43c53b5"
LAB_REV = "ae37b028ea415c91ea2bc32609efcd759ed2b974"
FROZEN_ASSETS = {
    "stand.onnx": "f645da599d4ca3d29ed273c8f4712620bb680d34977469ca3aeabe5bb9631c18",
    "walk.onnx": "7c82255b6905ffcc4468fa7f8ddcf7b70db168cf1042107ccab887cb6a8e5407",
    "g1_29dof_with_hand_rev_1_0.usd": "a7a2bab76981d19a1d76adecdfffec9b52afa34df9ba8e288ccedf410d3ce6bd",
    "g1_29dof_with_hand.urdf": "3dcb9c361753f464fa1f0238cdf800af842909628fd153733075607881c12d62",
}


def digest(path: Path) -> str:
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def source_check(path: Path, expected: str) -> None:
    revision = subprocess.check_output(["git", "-C", str(path), "rev-parse", "HEAD"], text=True).strip()
    if revision != expected:
        raise ValueError(f"Wrong source revision at {path}: {revision}")
    dirty = subprocess.check_output(["git", "-C", str(path), "status", "--porcelain", "--untracked-files=no"], text=True)
    if dirty:
        raise ValueError(f"Modified upstream source at {path}: {dirty}")


def preflight(args) -> dict:
    source_check(args.arena_source, ARENA_REV)
    source_check(args.lab_source, LAB_REV)
    for name, expected in FROZEN_ASSETS.items():
        if digest(args.homie_assets / name) != expected:
            raise ValueError(f"Artifact identity changed: {name}")
    return {
        "kind": "homie_original_physx_source_reference",
        "arena_revision": ARENA_REV, "isaaclab_revision": LAB_REV,
        "assets_sha256": FROZEN_ASSETS,
        "source_physics_hz": 200, "source_wbc_hz": 50,
        "bevy_rollout_verified": False, "task_rollout_verified": False,
        "source_stand_verified": False,
        "initial_root_xyz": [0.0, 0.0, 0.78], "initial_root_quaternion_xyzw": [0.0, 0.0, 0.0, 1.0],
        "navigation_command": [0.0, 0.0, 0.0], "pelvis_height_command": 0.75,
        "upper_body_joint_command": "28 zeros; lower 15 generated by original Homie",
        "ground_material": {"static_friction": 0.5, "dynamic_friction": 0.5, "restitution": 0.0},
        "known_comparison_difference": "Rapier diagnostic floor friction is 1.0; source default is 0.5",
        "requested_ticks": args.ticks, "min_root_height": args.min_height,
        "max_tilt_radians": args.max_tilt,
        "warmup_ticks_excluded": 0, "rollouts": [],
    }


def write_receipt(args, receipt):
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(receipt, indent=2, allow_nan=False) + "\n")


@contextmanager
def receipt_before_kit_exit(args, receipt):
    """Persist failures before upstream's shutdown uses os._exit()."""
    started = time.perf_counter()
    try:
        yield
    except Exception as error:
        receipt["error"] = repr(error)
        raise
    finally:
        receipt["source_seconds"] = time.perf_counter() - started
        receipt["peak_rss_kib"] = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        write_receipt(args, receipt)


def run_source(args, receipt):
    # AppLauncher must precede imports of simulation-dependent modules. The
    # default CLI has no visualizer, which the pinned launcher treats as headless.
    from isaaclab_arena.cli.isaaclab_arena_cli import get_isaaclab_arena_cli_parser
    from isaaclab_arena.utils.isaaclab_utils.simulation_app import SimulationAppContext

    launch_args = get_isaaclab_arena_cli_parser().parse_args([])
    launch_args.enable_cameras = False
    sys.argv = [sys.argv[0]]
    with SimulationAppContext(launch_args), receipt_before_kit_exit(args, receipt):
        import numpy as np
        import torch
        import warp as wp
        from isaaclab_arena.assets.object_library import GroundPlane
        from isaaclab_arena.embodiments.g1.g1 import G1WBCJointEmbodiment
        from isaaclab_arena.environments.arena_env_builder import ArenaEnvBuilder
        from isaaclab_arena.environments.arena_env_builder_cfg import ArenaEnvBuilderCfg
        from isaaclab_arena.environments.isaaclab_arena_environment import IsaacLabArenaEnvironment
        from isaaclab_arena.environments.isaaclab_arena_manager_based_env_cfg import set_control_rate_50hz
        from isaaclab_arena.scene.scene import Scene
        from isaaclab_arena.utils.pose import Pose
        from isaaclab.utils.assets import retrieve_file_path
        from isaaclab_arena.assets.nucleus import ARENA_NUCLEUS_DIR

        def tensor(value):
            if isinstance(value, torch.Tensor):
                return value
            if hasattr(value, "torch"):
                return value.torch
            return wp.to_torch(value)

        def configure(cfg):
            cfg = set_control_rate_50hz(cfg)
            cfg.episode_length_s = (args.ticks + 100) / 50
            return cfg

        source_urdf = Path(retrieve_file_path(f"{ARENA_NUCLEUS_DIR}/Arena/wbc_policy/robot_model/g1/g1_29dof_with_hand.urdf"))
        if digest(source_urdf) != FROZEN_ASSETS["g1_29dof_with_hand.urdf"]:
            raise ValueError("Source resolved a different WBC kinematic URDF")
        ground = GroundPlane()
        embodiment = G1WBCJointEmbodiment(enable_cameras=False)
        embodiment.set_initial_pose(Pose(position_xyz=(0.0, 0.0, 0.78), rotation_xyzw=(0.0, 0.0, 0.0, 1.0)))
        # Only storage location changes; preflight checks the original USD bytes.
        embodiment.scene_config.robot.spawn.usd_path = str(args.homie_assets / "g1_29dof_with_hand_rev_1_0.usd")
        description = IsaacLabArenaEnvironment(
            name="g1_homie_source_stand_diagnostic", scene=Scene(assets=[ground]),
            embodiment=embodiment, env_cfg_callback=configure,
        )
        cfg = ArenaEnvBuilderCfg(num_envs=1, seed=args.seed, solve_relations=False, resolve_on_reset=False)
        env = ArenaEnvBuilder(description, cfg).make_registered()
        raw = env.unwrapped
        robot = raw.scene["robot"]
        term = raw.action_manager.get_term("g1_action")
        for name, session in [("stand.onnx", term.wbc_policy.policy_1.session), ("walk.onnx", term.wbc_policy.policy_2.session)]:
            if digest(Path(session._model_path)) != FROZEN_ASSETS[name]:
                raise ValueError(f"Source remotely resolved different WBC weight: {name}")
        if not math.isclose(raw.cfg.sim.dt, 0.005) or raw.cfg.decimation != 4:
            raise ValueError("Source timing differs from 200/50 contract")
        receipt["joint_names"] = list(robot.joint_names)
        receipt["body_names"] = list(robot.body_names)
        # Read the compiled PhysX articulation instead of inferring how USD's
        # sentinel COM/inertia values were resolved, or how fixed links merged.
        plant = {name: tensor(getattr(robot.root_view, method)())[0].detach().cpu().numpy() for name, method in
                 [("mass", "get_masses"), ("com_pose_xyzw", "get_coms"), ("inertia_matrix", "get_inertias")]}
        receipt["compiled_plant"] = {
            name: {"values": np.where(np.isfinite(value), value, None).tolist(),
                   "nonfinite_indices": np.argwhere(~np.isfinite(value)).tolist()} for name, value in plant.items()
        }
        receipt["compiled_sensor_link_presence"] = {name: name in robot.body_names for name in
                                                    ["imu_in_pelvis", "d435_link", "imu_in_torso", "mid360_link"]}
        write_receipt(args, receipt)
        if not all(np.isfinite(value).all() for value in plant.values()):
            raise AssertionError("Compiled PhysX plant contains nonfinite mass/COM/inertia values")
        limits = tensor(robot.data.joint_pos_limits)[0].detach().cpu().numpy()
        receipt["joint_limits"] = limits.tolist()
        receipt["joint_limit_tolerance_radians"] = 0.001
        receipt["runtime_versions"] = {key: importlib.metadata.version(key) for key in ["isaacsim", "torch", "warp-lang", "onnxruntime"]}
        feet = [i for i, name in enumerate(robot.body_names) if name in ("left_ankle_roll_link", "right_ankle_roll_link")]

        def snapshot(tick):
            fields = {name: tensor(getattr(robot.data, name))[0].detach().cpu().numpy() for name in
                      ["root_link_pose_w", "root_link_vel_w", "joint_pos", "joint_vel", "projected_gravity_b"]}
            if not all(np.isfinite(value).all() for value in fields.values()):
                raise AssertionError(f"Nonfinite physical state at tick {tick}")
            gravity = fields["projected_gravity_b"]
            tilt = math.acos(float(np.clip(-gravity[2], -1, 1)))
            body_poses = tensor(robot.data.body_link_pose_w)[0].detach().cpu().numpy()
            targets = term.processed_actions[0].detach().cpu().numpy()
            if not np.isfinite(body_poses).all() or not np.isfinite(targets).all():
                raise AssertionError(f"Nonfinite body/action state at tick {tick}")
            violations = np.flatnonzero((fields["joint_pos"] < limits[:, 0] - 0.001) | (fields["joint_pos"] > limits[:, 1] + 0.001))
            return {"control_tick": tick, "physics_tick": tick * 4, "sample_phase": "control_boundary",
                    "sim_time_seconds": tick / 50, **{key: value.tolist() for key, value in fields.items()},
                    "foot_link_poses": body_poses[feet].tolist(), "tilt_radians": tilt,
                    "upright_cosine": float(-gravity[2]), "processed_joint_targets": targets.tolist(),
                    "joint_limit_violations": [{"joint": robot.joint_names[i], "q": float(fields["joint_pos"][i]),
                                                "limits": limits[i].tolist()} for i in violations]}

        trace_path = args.output.with_suffix(".jsonl")
        with trace_path.open("w") as trace:
            for repeat in range(args.repeats):
                env.reset(seed=args.seed)
                first = snapshot(0)
                row = {"repeat": repeat, "initial_state": first, "completed_ticks": 0, "passed": False}
                receipt["rollouts"].append(row)
                write_receipt(args, receipt)
                if not np.allclose(first["root_link_pose_w"][:3], [0, 0, 0.78], atol=1e-4):
                    raise AssertionError("Measured reset root differs from requested initial pose")
                for tick in range(args.ticks + 1):
                    if tick:
                        action = torch.zeros(env.action_space.shape, device=raw.device)
                        action[:, -4] = 0.75
                        _, _, terminated, truncated, _ = env.step(action)
                        if bool(terminated.any()) or bool(truncated.any()):
                            raise AssertionError(f"Unexpected episode reset at tick {tick}; cannot count as standing")
                    sample = snapshot(tick)
                    trace.write(json.dumps({"repeat": repeat, **sample}, allow_nan=False) + "\n")
                    trace.flush()
                    row["completed_ticks"] = tick
                    row["last_state"] = sample
                    if sample["joint_limit_violations"] and "first_joint_limit_violation" not in row:
                        row["first_joint_limit_violation"] = {"control_tick": tick, "physics_tick": tick * 4,
                                                               "joints": sample["joint_limit_violations"]}
                    write_receipt(args, receipt)
                    if sample["root_link_pose_w"][2] < args.min_height or sample["tilt_radians"] > args.max_tilt:
                        row["fall"] = {"control_tick": tick, "physics_tick": tick * 4,
                                       "height": sample["root_link_pose_w"][2], "tilt_radians": sample["tilt_radians"]}
                        break
                row["passed"] = "fall" not in row and "first_joint_limit_violation" not in row
                print(f"EVENT source stand repeat={repeat} passed={row['passed']} ticks={row['completed_ticks']}", flush=True)
        receipt["source_stand_verified"] = all(row["passed"] for row in receipt["rollouts"])
        receipt["trace_sha256"] = digest(trace_path)
        write_receipt(args, receipt)
        env.close()
        if not receipt["source_stand_verified"]:
            raise AssertionError("Source standing failed fall/finite/joint-limit checks; see receipt and trace")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arena-source", type=Path, required=True)
    parser.add_argument("--lab-source", type=Path, required=True)
    parser.add_argument("--homie-assets", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--run-source", action="store_true")
    parser.add_argument("--ticks", type=int, default=150)
    parser.add_argument("--repeats", type=int, default=2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--min-height", type=float, default=0.35)
    parser.add_argument("--max-tilt", type=float, default=math.pi / 3)
    args = parser.parse_args()
    if args.ticks < 1 or args.repeats < 1 or not 0 < args.min_height < 0.78 or not 0 < args.max_tilt < 1.57:
        parser.error("Invalid diagnostic duration or failure threshold")
    receipt = preflight(args)
    started = time.perf_counter()
    try:
        if args.run_source:
            run_source(args, receipt)
    except Exception as error:
        receipt["error"] = repr(error)
        raise
    finally:
        receipt["wall_seconds"] = time.perf_counter() - started
        receipt["peak_rss_kib"] = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        write_receipt(args, receipt)
        print(json.dumps(receipt), flush=True)


if __name__ == "__main__":
    main()
